name: "Code Validation"

on:
  push:
    branches-ignore:
      - main

jobs:
  job_terraform:
    name: "Terraform checks"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_GMAC_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: | 
          export TF_VAR_pat=${{ secrets.GMACTOKEN }}
          terraform plan -no-color
        continue-on-error: true
  
  job_checkov:
    runs-on: ubuntu-latest
    name: Checkov analyses
    needs: job_terraform
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform/
          framework: terraform
          output_format: sarif
